# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a08c65326e08ee7b26710faf1ab79a091d3a2bb5c3ea85fc9b169a82a04337a1f92cd53eb9bcd852296cf49efb4f710ce9a5d497659774583d859904e48b6531

test:
  secret_key_base: 4aa6723b55fe59be7f69daa161274501fc82aed3b1a4d8b2d20661d10055a59dfec3080b977a4085ebb7aa9508579751bc940f9545ebed80694adbc649644d74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
